# Generated by Django 6.0 on 2025-12-22 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_alter_product_options_review"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="name",
        ),
    ]
