# Generated by Django 6.0 on 2025-12-17 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0002_alter_cart_id"),
        ("product", "0002_alter_product_options_review"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="cartitem",
            unique_together={("cart", "product")},
        ),
    ]
